# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='content',
            field=models.ManyToManyField(blank=True, related_name='contents', to='channel.Video'),
        ),
    ]
