# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_auto_20170707_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='content',
            field=models.ManyToManyField(blank=True, related_name='contenting', to='channel.Video'),
        ),
    ]
