# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_channel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='season',
            name='netflix_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
