# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_auto_20170710_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
