# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_series_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='channel.Season'),
        ),
    ]
